export enum ActionTypes {
  START_LOADING = '@apps/START_LOADING',
  FINISH_LOADING = '@apps/FINISH_LOADING',
  SET_GALLERIES = '@apps/SET_GALLERIES',
  SET_FEATURED = '@apps/SET_FEATURED',
  SET_FILTERS = '@apps/SET_FILTERS',
  SET_SELECTED_FILTERS = '@apps/SET_SELECTED_FILTERS',
  SET_FILTERED_APPS = '@apps/SET_FILTERED_APPS',
}
